### ISSUE TITLE
if compilation fails after successfull git pull then autoupdater check will not update next time 

### ISSUE THREAD

**Issue by AGx10k** [ElrondNetwork/elrond-go-scripts-v2#1]
* git pull OK
 * compile FAIL (no disk space, no gcc installed, some other error doesnt matter)
 * next time it will compare LATEST tag vs CLONED tag it will look like it is already upgraded

suggested fix: check ./node --version against LATEST tag

**Comment by valentin-lup** [comment]
I'll look at it ASAP !

**Comment by alexandergalitski** [comment]
current auto update script is bad. it will probably work when everything is OK but it does not check for errors, edge situations and so on. it is (as a whole not the script itself) very complex because it relies on git, on successful compilation and so on.

harmony pangaea was a total mess but they had more or less good system of auto updates which worked with pre compiled binaries. it constantly checked in background for presence of new binaries, seamlessly downloaded them, installed and restarted. most users did not even know that it was working. even community managers did not know and have repeated mantra “please update, please restart” even when the thing updated itself successfully.

i insist on throwing away git checks and compilations and publishing binaries. make the work that can cause errors on one host and then just propagate binaries.

**Comment by AGx10k** [comment]
current auto update script is bad. it will probably work when everything is OK but it does not check for errors, edge situations and so on. it is (as a whole not the script itself) very complex because it relies on git, on successful compilation and so on.

harmony pangaea was a total mess but they had more or less good system of auto updates which worked with pre compiled binaries. it constantly checked in background for presence of new binaries, seamlessly downloaded them, installed and restarted. most users did not even know that it was working. even community managers did not know and have repeated mantra “please update, please restart” even when the thing updated itself successfully.

i insist on throwing away git checks and compilations and publishing binaries. make the work that can cause errors on one host and then just propagate the result.

**Comment by AGx10k** [comment]
also it can be spiced up by self checks and centralized variable of "current version". this is a way that NKN uses. here is the code to check current version. very simple and it works when they need urgently update network to new version. they just bump the current version and then it's operators work to updated their nodes if they want to be still able to receive rewards - https://github.com/nknorg/nkn/blob/bd1ed4b1e3777d52bd405d148f778dd75747acf4/nknd.go#L362

**Comment by AGx10k** [comment]
harmony's solution of checking new version: https://github.com/harmony-one/harmony/blob/85b7c3bb2c6dfff398318f672f44e14317749517/scripts/node.sh#L464

**Comment by valentin-lup** [comment]
Fixed ! Thanks for all the great input ! :)
